-- Script de configuración de base de datos para el Sistema de Evaluación de Proveedores
-- Ejecuta este script en el Editor SQL de Supabase para crear todas las tablas y relaciones necesarias.

-- 1. Tabla de Contraseña de Administrador
CREATE TABLE IF NOT EXISTS admin_password (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password_hash TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de Evaluadores
CREATE TABLE IF NOT EXISTS evaluadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabla de Proveedores
CREATE TABLE IF NOT EXISTS proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    tipo TEXT NOT NULL, -- 'PRODUCTO' o 'SERVICIO'
    email TEXT,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tabla de Asignaciones (Relación Evaluador - Proveedor)
CREATE TABLE IF NOT EXISTS asignaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluador_id BIGINT REFERENCES evaluadores(id) ON DELETE CASCADE,
    proveedor_id BIGINT REFERENCES proveedores(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL, -- 'PRODUCTO' o 'SERVICIO'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(evaluador_id, proveedor_id, tipo)
);

-- 5. Tabla de Evaluaciones (Resultados de las encuestas)
CREATE TABLE IF NOT EXISTS evaluaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluador_id BIGINT REFERENCES evaluadores(id),
    proveedor_id BIGINT REFERENCES proveedores(id),
    tipo_proveedor TEXT NOT NULL,
    correo_proveedor TEXT,
    respuestas JSONB NOT NULL, -- Almacena las respuestas detalladas
    resultado_final NUMERIC,
    fecha_evaluacion TIMESTAMP WITH TIME ZONE, -- Fecha seleccionada en el calendario
    "año" INTEGER, -- Año de la evaluación (Atención: lleva tilde según el código)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Tabla de Configuración de la Evaluación
CREATE TABLE IF NOT EXISTS config_evaluacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT,
    descripcion TEXT,
    objetivo TEXT,
    items_producto JSONB,
    items_servicio JSONB,
    anio_encuesta INTEGER,
    fecha_inicio_encuesta TIMESTAMP WITH TIME ZONE,
    fecha_fin_encuesta TIMESTAMP WITH TIME ZONE,
    zona_horaria_encuesta TEXT DEFAULT 'America/Santiago',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Tabla de Evaluaciones del Administrador (Overrides)
CREATE TABLE IF NOT EXISTS evaluaciones_admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor TEXT NOT NULL,
    item TEXT NOT NULL,
    valor NUMERIC,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(proveedor, item)
);

-- Habilitar Row Level Security (RLS) es recomendado, pero para este setup simple lo dejaremos abierto
-- o configuraremos políticas públicas si es necesario.
-- Por defecto en Supabase las tablas nuevas pueden requerir políticas si RLS está habilitado.
-- Deshabilitamos RLS para facilitar el inicio (ADVERTENCIA: No recomendado para producción con datos sensibles expuestos)
ALTER TABLE admin_password ENABLE ROW LEVEL SECURITY;
ALTER TABLE evaluadores ENABLE ROW LEVEL SECURITY;
ALTER TABLE proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE asignaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE evaluaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE config_evaluacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE evaluaciones_admin ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso público (Para que funcione sin autenticación de usuario de Supabase, 
-- ya que la app maneja su propia lógica simple o usa la anon key para todo)
-- Permite lectura y escritura pública usando la anon key.

CREATE POLICY "Acceso total a admin_password" ON admin_password FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total a evaluadores" ON evaluadores FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total a proveedores" ON proveedores FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total a asignaciones" ON asignaciones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total a evaluaciones" ON evaluaciones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total a config_evaluacion" ON config_evaluacion FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total a evaluaciones_admin" ON evaluaciones_admin FOR ALL USING (true) WITH CHECK (true);

-- Insertar Configuración Inicial por Defecto
INSERT INTO config_evaluacion (titulo, descripcion, objetivo, items_producto, items_servicio, anio_encuesta)
VALUES (
    'Evaluación de Proveedores',
    'Este sistema permite evaluar el desempeño de nuestros proveedores mediante un proceso estructurado y objetivo.',
    'Medir y mejorar continuamente la calidad de nuestros proveedores.',
    '[
        {"nombre": "Condiciones Financieras de Pago", "ponderacion": 10},
        {"nombre": "Información de certificación o implementación respecto a alguna ISO", "ponderacion": 4},
        {"nombre": "Comunicación fluida con el cliente", "ponderacion": 4},
        {"nombre": "Reacción frente a nuevos requerimientos", "ponderacion": 5},
        {"nombre": "Información técnica de los productos (Calidad, Medio Ambiente y Seguridad)", "ponderacion": 2},
        {"nombre": "Cumplimiento de plazos de entrega, horarios de bodega y documentación", "ponderacion": 65},
        {"nombre": "Certificación del producto del proveedor", "ponderacion": 10}
    ]'::jsonb,
    '[
        {"nombre": "Comportamiento seguro durante la prestación del servicio", "ponderacion": 10},
        {"nombre": "Cumplimiento de la oportunidad en la realización del servicio", "ponderacion": 33},
        {"nombre": "Calidad del servicio", "ponderacion": 33},
        {"nombre": "Comunicación fluida con el prestador del servicio", "ponderacion": 7},
        {"nombre": "Reacción del prestador frente a nuevos requerimientos", "ponderacion": 10},
        {"nombre": "Publicación del estado en regla de las partes relevantes y otra información relevante para el usuario AURA", "ponderacion": 7}
    ]'::jsonb,
    EXTRACT(YEAR FROM CURRENT_DATE)
);
